import { useEffect, useState } from "react";
import { getBrief } from "../api";

function CopyButton({ text }) {
  const [copied, setCopied] = useState(false);
  function copy() {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }
  return (
    <button className="btn btn-secondary btn-sm" onClick={copy}>
      <span role="status" aria-live="polite">{copied ? "Copied!" : "Copy brief"}</span>
    </button>
  );
}

function BriefText({ text }) {
  const lines = text.split("\n");
  const elements = [];
  let key = 0;

  for (const line of lines) {
    if (line.startsWith("## ")) {
      elements.push(
        <h2 key={key++} className="subhead" style={{
          marginTop: "var(--sp-5)",
          marginBottom: "var(--sp-2)",
        }}>
          {line.slice(3)}
        </h2>
      );
    } else if (line.trim() === "") {
      elements.push(<div key={key++} style={{ height: "var(--sp-2)" }} />);
    } else {
      elements.push(
        <p key={key++} className="body-text" style={{ margin: 0 }}>
          {line}
        </p>
      );
    }
  }
  return <div>{elements}</div>;
}

export default function BriefView({ topicId }) {
  const [brief, setBrief] = useState(null);
  const [loading, setLoading] = useState(true);
  const [missing, setMissing] = useState(false);

  useEffect(() => {
    if (!topicId) return;
    setLoading(true);
    setMissing(false);
    getBrief(topicId)
      .then(setBrief)
      .catch(() => setMissing(true))
      .finally(() => setLoading(false));
  }, [topicId]);

  if (loading) {
    return (
      <div className="card" role="status" aria-live="polite">
        <span className="sr-only">Loading strategy brief…</span>
        <div className="skel" style={{ height: 12, width: "40%", marginBottom: "var(--sp-4)" }} />
        {Array.from({ length: 6 }).map((_, i) => (
          <div key={i} className="skel" style={{ height: 10, width: `${70 + (i % 3) * 10}%`, marginBottom: "var(--sp-2)" }} />
        ))}
      </div>
    );
  }

  if (missing) {
    return (
      <div className="card" role="status" aria-live="polite" style={{ textAlign: "center", padding: "var(--sp-8) var(--sp-6)" }}>
        <div style={{ fontSize: "var(--text-3xl)", marginBottom: "var(--sp-4)" }} aria-hidden="true">🤖</div>
        <div className="subhead" style={{ marginBottom: "var(--sp-2)" }}>
          The strategy brief isn’t ready yet
        </div>
        <div className="body-text" style={{ color: "var(--text-3)", maxWidth: 340, margin: "0 auto" }}>
          We haven’t generated an AI strategy brief for this topic yet. Check back shortly, or explore the partner shortlist and network map in the meantime.
        </div>
      </div>
    );
  }

  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "var(--sp-3)", marginBottom: "var(--sp-4)" }}>
        <p className="muted" style={{ margin: 0 }}>
          AI strategy brief · generated by {brief.model || "Groq"}
          {brief.generated_at && (
            <> · {new Date(brief.generated_at).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}</>
          )}
        </p>
        <CopyButton text={brief.text} />
      </div>

      <div className="card">
        <BriefText text={brief.text} />
      </div>
    </div>
  );
}
